### ISSUE TITLE
Replacing torch.kron with fastkron 

### ISSUE THREAD

**Issue by RaulPPelaez** [abhijangda/fastkron#2]
Hi, thanks for your nice contribution!

Are there any plans to write a replacement for `torch.kron`?
Either in torch itself or providing a custom CUDA/C++ extension through this repo.

That would entail writing a backwards pass for fastkron as well.

**Comment by abhijangda** [comment]
Hi Raul,

Yes, the plan is to provide a Python extension that does Kronecker Matrix-Matrix Multiplication. However, I think that requires a few months. I am not sure about the backward pass yet. I think that is more evolved.

**Comment by abhijangda** [comment]
Hi Raul,
Now you can use torch extension with a backward pass. Just do `pip install pyfastkron`.
